
logging:
  config: classpath:log4j2-dev.xml

me:
  uploader:
    processor: cos
sdk:
  tencent:
    cloud:
      host: http://file.qijin.tech
      bucket: file-1300635595
      region: ap-chengdu
      routes[0]:
        scene: file
        host: http://file.qijin.tech
        bucket: file-1300635595
        region: ap-chengdu
      routes[1]:
        scene: img
        host: http://img.qijin.tech
        bucket: img-1300635595
        region: ap-beijing

spring:
  profiles:
    active: dev
  datasource:
    druid:
      im:
        url: jdbc:mysql://127.0.0.1:3306/cell_im?useUnicode=true&characterEncoding=utf-8
        username: admin
        password: Admin_@123
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 10
        max-active: 30
        min-idle: 5
        max-wait: 60
      gim:
        url: jdbc:mysql://127.0.0.1:3306/cell_gim?useUnicode=true&characterEncoding=utf-8
        username: admin
        password: Admin_@123
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 10
        max-active: 30
        min-idle: 5
        max-wait: 60
    freemarker:
      suffix: .ftl
      template-loader-path: classpath:/freemarker/
      cache: false
      charset: utf-8

# swagger config
swagger:
  enable: true
